version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    groups:
      npm-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      npm-dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "sunday"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "composer"
